server/pubs_ui/__init__.py
import json
import logging
import os
import sys

from authlib.integrations.flask_client import OAuth

from flask import Flask, request
from flask_caching import Cache
from flask_images import Images
from flask_mail import Mail
from graypy import GELFTCPHandler

from whitenoise import WhiteNoise

from .custom_filters import display_publication_info, date_format, w3c_date

# pylint: disable=C0103


def _create_log_handlers(graylog_config=None, log_level=logging.INFO):
    """
    Create a handler object(s). A stream handler will always be created to
    send output to STDOUT.

    If a graylog configuration is specified, a handler will be created to
    push to the graylog server.

    :param dict graylog_config: optional dictionary with `host` and `port` keys, which specify
        the Graylog server's host and the port being listened to. For example, `{'host': '127.0.0.1', 'port': 12201}`.
    :param log_level: the log level to use
    :return: a list of handlers
    :rtype: list

    """

    handlers = [logging.StreamHandler(sys.stdout)]
    if graylog_config is not None:
        handlers.append(GELFTCPHandler(graylog_config['host'], graylog_config['port']))

    def configure_handler(some_handler):
        formatter = logging.Formatter('%(asctime)s - %(levelname)s - {%(pathname)s:L%(lineno)d} - %(message)s')
        some_handler.setFormatter(formatter)
        some_handler.setLevel(log_level)

    map(configure_handler, handlers)
    return handlers


app = Flask(__name__.split()[0], instance_relative_config=True)

# Loads configuration information from config.py and instance/config.py
app.config.from_object('config')  # load configuration before passing the app object to other things
if ('NO_INSTANCE_CONFIG') not in os.environ:
    app.config.from_pyfile('config.py', silent=True)

@app.before_request
def log_request():
    if app.config.get('LOGGING_ON'):
        request_str = str(request)
        request_headers = str(request.headers)
        log_str = 'Request: ({0}); Headers: ({1})'.format(request_str, request_headers)
        app.logger.info(log_str)


if app.config.get('LOGGING_ON'):
    app_log_handlers = _create_log_handlers(app.config.get('GRAYLOG_CONFIG'))
    for app_log_handler in app_log_handlers:
        app.logger.addHandler(app_log_handler)
images = Images(app)
mail = Mail(app)
app.view_functions['images'] = images.handle_request
app.jinja_env.filters['display_pub_info'] = display_publication_info
app.jinja_env.filters['date_format'] = date_format
app.jinja_env.filters['w3c_date'] = w3c_date
app.jinja_env.globals.update(wsgi_str=app.config['WSGI_STR'])
app.jinja_env.globals.update(GOOGLE_ANALYTICS_CODE=app.config['GOOGLE_ANALYTICS_CODE'])
app.jinja_env.globals.update(GOOGLE_WEBMASTER_TOOLS_CODE=app.config['GOOGLE_WEBMASTER_TOOLS_CODE'])
app.jinja_env.globals.update(LAST_MODIFIED=app.config.get('DEPLOYED'))
app.jinja_env.globals.update(ANNOUNCEMENT_BLOCK=app.config['ANNOUNCEMENT_BLOCK'])

#Enable authentication
oauth = OAuth(app)
oauth.register('pubsauth',
               client_kwargs = {'verify': app.config.get('VERIFY_CERT', True)}
               )

# Set up the cache
cache = Cache(app, config={
    'CACHE_TYPE': app.config['CACHE_TYPE'],
    'CACHE_REDIS_HOST': app.config['CACHE_REDIS_HOST'],
    'CACHE_KEY_PREFIX': app.config['CACHE_KEY_PREFIX']
})

# Load static assets manifest file, which maps source file names to the
# corresponding versioned/hashed file name.
_manifest_path = app.config.get('ASSET_MANIFEST_PATH')
if _manifest_path:
    with open(_manifest_path, 'r') as f:
        app.config['ASSET_MANIFEST'] = json.loads(f.read())
        app.logger.info(app.config['ASSET_MANIFEST'])

# Enable Whitenoise which will allow the application when using nginx to serve out the static assets.
if app.config['STATIC_ASSET_PATH']:
    app.wsgi_app = WhiteNoise(app.wsgi_app, root=app.config['STATIC_ASSET_PATH'], prefix='static/')

# Enable CORS, if specified in the configuration.
if app.config.get('FLASK_CORS'):
    from flask_cors import CORS
    CORS(app)

from .auth.views import auth_blueprint
from .manager.views import manager
from .pubswh.views import pubswh
from .metrics.views import metrics
from . import filters  # pylint: disable=C0413

app.register_blueprint(auth_blueprint)
app.register_blueprint(manager, url_prefix='/manager')
app.register_blueprint(metrics, url_prefix='/metrics')
app.register_blueprint(pubswh)

server/pubs_ui/manager/__init__.py
__author__ = 'mbucknel'

server/pubs_ui/metrics/views.py
"""
Metrics blueprint views
"""
# pylint: disable=C0103,C0111

import random
import time

from flask import Blueprint, render_template, request, jsonify, Response
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from httplib2 import Http
from oauth2client.service_account import ServiceAccountCredentials
from requests import get

from .. import app, cache


metrics = Blueprint('metrics', __name__,
                    template_folder='templates',
                    static_folder='static',
                    static_url_path='/metrics/static')

verification_cert = app.config.get('VERIFY_CERT', True)


def _handle_http_certificates():
    if isinstance(verification_cert, str):
        httplib_http = Http(ca_certs=verification_cert)
    elif isinstance(verification_cert, bool):
        httplib_http = Http(disable_ssl_certificate_validation=(not verification_cert))
    else:
        httplib_http = Http()
    return httplib_http


http = _handle_http_certificates()


try:
    credentials = ServiceAccountCredentials.from_json_keyfile_name(
        app.config.get('GA_KEY_FILE_PATH'),
        app.config.get('GA_OAUTH2_SCOPE')
    )
    analytics = build(
        'analytics', 'v4',
        http=credentials.authorize(http),
        discoveryServiceUrl=app.config.get('GA_DISCOVERY_URI'))
except IOError:
    analytics = None


def make_cache_key_from_request_data():
    return request.data.decode()


@metrics.route('/publications/acquisitions/')
def publications_aquisitions():
    return render_template('metrics/publications_acquisitions.html')


@metrics.route('/publications/')
def publications():
    return render_template('metrics/publications.html')


@metrics.route('/publication/<pubsid>/')
def publication(pubsid):
    r = get(app.config['PUB_URL'] + 'publication/' + pubsid, params={'mimetype': 'json'}, verify=app.config['VERIFY_CERT'])
    pub = r.json() if r.status_code == 200 else {}
    return render_template('metrics/publication.html', pubsid=pubsid, publication=pub)


@metrics.route('/gadata/', methods=['POST'])
@cache.cached(86400, make_cache_key_from_request_data)
def gadata():
    view_id = app.config.get('GA_PUBS_VIEW_ID')
    report_requests = request.get_json()
    for r in report_requests:
        r.update({'viewId': view_id})
    for n in range(0, 5):
        try:
            report_response = analytics.reports().batchGet(
                # Pass so that the quota to limit 10 queries per second per IP uses the client's IP.
                quotaUser=request.remote_addr,
                body={
                    'reportRequests': report_requests
                }
            ).execute()
            response = jsonify(report_response)

            break
        except HttpError as error:
            response = Response(response=error.content,
                                status=int(error.resp['status']),
                                mimetype='application/json')
            if error.resp.reason in [
                    'userRateLimitExceeded',
                    'rateLimitExceeded'
                    'quotaExceeded']:
                # Assign a response but try again until succeeds or loop exits
                response = Response
                time.sleep((2 ** n) + random.random())
            else:
                break

    return response

server/pubs_ui/pubswh/views.py
"""
pubswh blueprint views
"""
# pylint: disable=C0103,C0301,C0111,W0613

from datetime import date, timedelta
import json
from operator import itemgetter
from urllib.parse import urlencode, urljoin
import random

import arrow
from dateutil import parser as dateparser
from requests import get
import tablib

from flask import render_template, abort, request, Response, jsonify, url_for, redirect, Blueprint
from flask_paginate import Pagination
from flask_mail import Message

from ..auth.views import authentication_required, is_authenticated, get_auth_header
from .. import app, mail, cache
from .canned_text import EMAIL_RESPONSE
from .forms import ContactForm, NumSeries, PublicAccessContactForm
from .utils import (pull_feed, create_display_links,
                    SearchPublications, change_to_pubs_test,
                    munge_pubdata_for_display, extract_related_pub_info,
                    update_geographic_extents, generate_sb_data, create_store_info,
                    get_altmetric_badge_img_links, generate_dublin_core, get_crossref_data, get_published_online_date,
                    check_public_access, get_unpaywall_data, make_chapter_data_for_display)
from .xml_transformations import transform_xml_full

pubswh = Blueprint('pubswh', __name__,
                   template_folder='templates',
                   static_folder='static',
                   static_url_path='/pubswh/static')
pub_url = app.config['PUB_URL']
lookup_url = app.config['LOOKUP_URL']
search_url = app.config['BASE_SEARCH_URL']
contact_recipients = app.config['CONTACT_RECIPIENTS']
ipds_contact_recipients = app.config.get('IPDS_CONTACT_RECIPIENTS')
robots_welcome = app.config.get('ROBOTS_WELCOME')
json_ld_id_base_url = app.config.get('JSON_LD_ID_BASE_URL')
google_webmaster_tools_code = app.config.get('GOOGLE_WEBMASTER_TOOLS_CODE')
preview_endpoint_url = app.config.get('PREVIEW_ENDPOINT_URL')
crossref_endpoint = app.config['CROSSREF_ENDPOINT']


# should requests verify the certificates for ssl connections
verify_cert = app.config['VERIFY_CERT']


def make_cache_key(*args, **kwargs):
    path = request.path
    args = str(hash(frozenset(request.args.items(True))))
    return path + args


@pubswh.errorhandler(404)
def page_not_found():
    # pylint: disable=W0613
    return render_template('pubswh/404.html'), 404


@pubswh.route("/preview/<index_id>")
@authentication_required
def restricted_page(index_id):
    """
    web page which is restricted and requires the user to be logged in.
    """

    # generate the auth header from the request
    auth_header = get_auth_header()

    # build the url to call the endpoint
    published_status = get(pub_url + 'publication/' + index_id,
                           params={'mimetype': 'json'}, verify=verify_cert).status_code

    # go out to manage and get the record
    response = get(preview_endpoint_url+index_id+'/preview', headers=auth_header, verify=verify_cert,
                   params={'mimetype': 'json'})

    if response.status_code == 200:
        record = response.json()
        pubdata = munge_pubdata_for_display(record, json_ld_id_base_url)
        pub_doi = pubdata.get('doi')
        pub_altmetric_badges, pub_altmetric_details = get_altmetric_badge_img_links(pub_doi, verify=verify_cert)
        small_badge = pub_altmetric_badges['small'] if pub_altmetric_badges is not None else None
        altmetric_links = {'image': small_badge, 'details': pub_altmetric_details}
        pubdata['altmetric'] = altmetric_links
        related_pubs = extract_related_pub_info(pubdata)
        if 'mimetype' in request.args and request.args.get("mimetype") == 'json':
            return jsonify(pubdata)
        return render_template("pubswh/preview.html", indexID=index_id, pubdata=pubdata, related_pubs=related_pubs)

    # if the publication has been published (so it is out of manage) redirect to the right URL
    elif response.status_code == 404 and published_status == 200:
        return redirect(url_for('pubswh.publication', index_id=index_id))

    elif response.status_code == 404 and published_status == 404:
        return render_template('pubswh/404.html'), 404


@pubswh.route('/robots.txt')
def robots():
    return render_template('pubswh/robots.txt', robots_welcome=robots_welcome)


@pubswh.route('/opensearch.xml')
def open_search():
    return render_template('pubswh/opensearch.xml')


@pubswh.route('/' + google_webmaster_tools_code + '.html')
def webmaster_tools_verification():
    return render_template('pubswh/google_site_verification.html')


@pubswh.route('/')
@cache.cached(timeout=300, key_prefix=make_cache_key, unless=is_authenticated)
def index():
    sp = SearchPublications(search_url)
    recent_publications_resp = sp.get_pubs_search_results(params={'pub_x_days': 7,
                                                                  'page_size': 6})  # bring back recent publications

    recent_pubs_content = recent_publications_resp[0]
    try:
        pubs_records = recent_pubs_content['records']
        for record in pubs_records:
            record = create_display_links(record)

    except TypeError:
        pubs_records = []  # return an empty list recent_pubs_content is None (e.g. the service is down)
    return render_template('pubswh/home.html',
                           recent_publications=pubs_records)


# contact form
@pubswh.route('/public_access_contact', methods=['GET', 'POST'])
def pub_access_contact():
    contact_form = PublicAccessContactForm()
    if request.method == 'POST':
        if contact_form.validate_on_submit():
            human_name = contact_form.name.data
            human_email = contact_form.email.data
            if human_name:
                sender_str = '({name}, {email})'.format(name=human_name, email=human_email)
            else:
                sender_str = '({email})'.format(email=human_email)
            # this is want Remedy filters on to determine if an email goes to the pubs support group
            subject_line = 'Pubs Warehouse Public Access request Comments'
            originating_page = contact_form.originating_page.data
            message_body = contact_form.message.data
            message_content = EMAIL_RESPONSE.format(contact_str=sender_str,
                                                    message_body=message_body,
                                                    originating_page=originating_page)
            msg = Message(subject=subject_line,
                          sender=(human_name, human_email),
                          reply_to=('IPDS_Help', 'GS_Help_IPDS@usgs.gov'),
                          # this is not what Remedy filters on to determine if a message
                          # goes to the pubs support group...
                          recipients=ipds_contact_recipients,
                          # will go to gs_ipds_help@usgs.gov if application has DEBUG = False
                          body=message_content)
            mail.send(msg)
            # redirect to a conf page after successful validation and message sending
            return redirect(url_for('pubswh.pub_access_contact_confirmation'))
        else:
            # redisplay the form with errors if validation fails
            return render_template('pubswh/pub_access_contact.html', contact_form=contact_form)

    contact_referrer = request.referrer
    contact_form.originating_page.data = 'Originating Page: {}'.format(contact_referrer)
    title = request.args.get('title')
    index_id = request.args.get('index_id')
    contact_form.message.data = 'I would like to request the full-text public access version of the following ' \
                                'publication: {0} \n\n USGS support team: Get more details on this publication here:' \
                                ' https://pubs.er.usgs.gov/public_access_details/{1}'.format(title, index_id)
    return render_template('pubswh/pub_access_contact.html', contact_form=contact_form)


@pubswh.route('/public_access_contact_confirm')
def pub_access_contact_confirmation():
    confirmation_message = 'Thank you for contacting the USGS Publications Warehouse Public Access support team.'
    return render_template('pubswh/pub_access_contact_confirm.html', confirm_message=confirmation_message)


@pubswh.route('/public_access_details/<index_id>')
@authentication_required
def public_access_details(index_id):
    # build the url to call the endpoint
    r = get(pub_url + 'publication/' + index_id, params={'mimetype': 'json'}, verify=verify_cert)
    if r.status_code in [404, 406]:  # a 406 pretty much always means that it is some sort of other weird malformed URL.
        return render_template('pubswh/404.html'), 404

    pubreturn = r.json()
    pubdata = munge_pubdata_for_display(pubreturn, json_ld_id_base_url)

    return render_template('pubswh/pub_access_data.html', indexID=index_id, pubdata=pubdata, related_pubs=None)


# contact form
@pubswh.route('/contact', methods=['GET', 'POST'])
def contact():
    contact_form = ContactForm()
    if request.method == 'POST':
        if contact_form.validate_on_submit():
            human_name = contact_form.name.data
            human_email = contact_form.email.data
            if human_name:
                sender_str = '({name}, {email})'.format(name=human_name, email=human_email)
            else:
                sender_str = '({email})'.format(email=human_email)
            subject_line = 'Pubs Warehouse User Comments'  # this is want Remedy filters on to determine if an email
            # goes to the pubs support group
            originating_page = contact_form.originating_page.data
            message_body = contact_form.message.data
            message_content = EMAIL_RESPONSE.format(contact_str=sender_str,
                                                    message_body=message_body,
                                                    originating_page=originating_page)
            msg = Message(subject=subject_line,

server/pubs_ui/templates/partials/footer.html
<footer class="usa-footer" role="contentinfo">
    <nav class="usa-footer-primary-section" aria-label="Footer Navigation">
        <div class="usgs-footer-nav">
            <a class="usgs-footer-link" href="https://www.doi.gov/privacy">DOI Privacy Policy</a> |
            <a class="usgs-footer-link" href="https://www.usgs.gov/laws/policies_notices.html">Legal</a> |
            <a class="usgs-footer-link" href="https://www2.usgs.gov/laws/accessibility.html">Accessibility</a> |
            <a class="usgs-footer-link" href="https://www.usgs.gov/sitemap.html">Site Map</a> |
            <a class="usgs-footer-link" href="https://answers.usgs.gov/">Contact USGS</a>
        </div>
        <div class="usgs-footer-nav">
            <a class="usgs-footer-link" href="https://www.doi.gov/">U.S. Department of the Interior</a> |
            <a class="usgs-footer-link" href="https://www.doioig.gov/">DOI Inspector General</a> |
            <a class="usgs-footer-link" href="https://www.whitehouse.gov/">White House</a> |
            <a class="usgs-footer-link" href="https://www.whitehouse.gov/omb/management/egov/">E-gov</a> |
            <a class="usgs-footer-link" href="https://www.doi.gov/pmb/eeo/no-fear-act">No Fear Act</a> |
            <a class="usgs-footer-link" href="https://www2.usgs.gov/foia">FOIA</a>
        </div>
    </nav>
</footer>

server/pubs_ui/templates/partials/header.html
{% macro usgs_header(enable_nav, is_authenticated) -%}
    <a class="usa-skipnav" href="#main-content">Skip to main content</a>

    <section class="usa-banner maxw-full" aria-label="Official government website">
        <div class="usa-accordion">
            <header class="usa-banner__header">
                <div class="usa-banner__inner content-container">
                    <div class="grid-col-auto">
                        <img class="usa-banner__header-flag" src="{{ 'img/us_flag_small.png' | asset_url }}" alt="U.S. flag">
                    </div>
                    <div class="grid-col-fill tablet:grid-col-auto">
                        <p class="usa-banner__header-text">An official website of the United States government</p>
                        <p class="usa-banner__header-action" aria-hidden="true">Here’s how you know</p>
                    </div>
                    <button class="usa-accordion__button usa-banner__button"
                            aria-expanded="false" aria-controls="gov-banner">
                        <span class="usa-banner__button-text">Here’s how you know</span>
                    </button>
                </div>
            </header>
            <div class="usa-banner__content usa-accordion__content" id="gov-banner">
                <div class="grid-row grid-gap-lg">
                    <div class="usa-banner__guidance tablet:grid-col-6">
                        <img class="usa-banner__icon usa-media-block__img" src="{{ 'img/icon-dot-gov.svg' | asset_url }}"
                             alt="Dot gov">
                        <div class="usa-media-block__body">
                            <p>
                                <strong>Official websites use .gov</strong>
                                <br/>
                                A <strong>.gov</strong> website belongs to an official government organization in the
                                United States.
                            </p>
                        </div>
                    </div>
                    <div class="usa-banner__guidance tablet:grid-col-6">
                        <img class="usa-banner__icon usa-media-block__img" src="{{ 'img/icon-https.svg' | asset_url }}"
                             alt="Https">
                        <div class="usa-media-block__body">
                            <p>
                                <strong>Secure .gov websites use HTTPS</strong>
                                <br/>
                                A <strong>lock</strong> (
                                <span class="icon-lock">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="52" height="64" viewBox="0 0 52 64" class="usa-banner__lock-image" role="img" aria-labelledby="banner-lock-title banner-lock-description"><title id="banner-lock-title">Lock</title><desc id="banner-lock-description">A locked padlock</desc><path fill="#000000" fill-rule="evenodd" d="M26 0c10.493 0 19 8.507 19 19v9h3a4 4 0 0 1 4 4v28a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h3v-9C7 8.507 15.507 0 26 0zm0 8c-5.979 0-10.843 4.77-10.996 10.712L15 19v9h22v-9c0-6.075-4.925-11-11-11z"/></svg>
                                </span>
                                ) or <strong>https://</strong> means you’ve safely connected to the .gov website. Share sensitive information only on official, secure websites.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="usa-overlay"></div>

    <header class="usa-header usa-header--extended usgs-header site-header" role="banner">
        <div class="usgs-header-container">
            <div class="usa-navbar">
                <div class="usa-logo" id="extended-logo">
                    <img alt="USGS Home" src="{{ 'img/USGS_logo.svg' | asset_url }}"/>
                </div>
                <button class="usa-menu-btn">Menu</button>
            </div>
        </div>

        {% if enable_nav %}
            <nav role="navigation" class="usa-nav">
                <div>
                    <button class="usa-nav__close"><img src="{{ 'img/close.svg' | asset_url }}" alt="close"></button>
                    <ul class="usa-nav__primary usa-accordion">
                        <li class="usa-nav__primary-item">
                            <a class="usa-nav__link" href="{{ url_for('pubswh.index') }}">USGS Publications Warehouse</a>
                        </li>
                        <li class="usa-nav__primary-item">
                            <button class="usa-accordion__button usa-nav__link"
                                    aria-expanded="false"
                                    aria-controls="explore-section">
                                <span>Explore</span>
                            </button>
                            <ul id="explore-section" class="usa-nav__submenu">
                                <li class="usa-nav__submenu-item">
                                 <a href="{{ url_for('pubswh.new_pubs') }}">Explore recent publications by USGS authors</a>
                                </li>
                                <li class="usa-nav__submenu-item">
                                    <a href="{{ url_for('pubswh.browse_types') }}">
                                        Browse all of Pubs Warehouse by publication type and year
                                    </a>
                                </li>
                           </ul>
                        </li>
                        <li class="usa-nav__primary-item">
                            <button class="usa-accordion__button usa-nav__link"
                                    aria-expanded="false"
                                    aria-controls="documentation-section">
                                <span>Documentation</span>
                            </button>
                            <ul id="documentation-section" class="usa-nav__submenu">
                                <li class="usa-nav__submenu-item">
                                    <a href="{{ url_for('pubswh.faq') }}">FAQs</a>
                                </li>
                                <li class="usa-nav__submenu-item">
                                  <a href="{{ url_for('pubswh.web_service_docs') }}">Web service documentation</a>
                                </li>
                                <li class="usa-nav__submenu-item">
                                  <a href="{{ url_for('pubswh.other_resources') }}">Other resources</a>
                                </li>
                                <li class="usa-nav__submenu-item">
                                    <a href="{{ url_for('pubswh.usgs_series') }}">
                                        Descriptions of US Geological Survey Report Series
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="usa-nav__primary-item">
                            <a class="usa-nav__link" href="{{ url_for('pubswh.contact') }}">Contact</a>
                        </li>
                        {% if is_authenticated %}
                            <li class="usa-nav__primary-item">
                                <a class="usa-nav__link" href="{{ url_for('auth.logout', next=request.url) }}">
                                    Logout
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                    <div class="usa-nav__secondary">
                        <form class="usa-search usa-search--small" action="{{ url_for('pubswh.search_results') }}" method="get">
                            <div role="search">
                                <label class="usa-sr-only" for="extended-search-field-small">Search</label>
                                <input class="usa-input" id="extended-search-field-small" type="search" name="q">
                                <button class="usa-button" type="submit">
                                    <span class="usa-sr-only">Search</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </nav>
        {% endif %}
    </header>
{% endmacro %}