server/pubs_ui/pubswh/forms.py
"""
Forms for the pubswh Blueprint
"""
# pylint: disable=C0111,C0301

from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, TextAreaField, SubmitField, validators, BooleanField
from wtforms.fields.html5 import DateField


__author__ = 'jameskreft'


class ContactForm(FlaskForm):
    name = StringField('Name', description='your name')
    # email validator also makes this a required field... a blank email is considered invalid
    email = StringField('Email', [validators.Email()])
    originating_page = StringField('Originating Page')
    message = TextAreaField('Message')
    recaptcha = RecaptchaField()
    submit = SubmitField('Send')


class PublicAccessContactForm(FlaskForm):
    name = StringField('Name')
    # email validator also makes this a required field... a blank email is considered invalid
    email = StringField('Email', [validators.Email()])
    originating_page = StringField('Originating Page')
    message = TextAreaField('Message', default='I would like to request the full-text public access version of the following publication')
    recaptcha = RecaptchaField()
    submit = SubmitField('Send')


class NumSeries(FlaskForm):
    num_series = BooleanField('Only USGS Numbered Series')
    date_range = DateField('Include publications back to date:   ')

server/pubs_ui/manager/views.py
"""
Manager blueprint views
"""
# pylint: disable=C0103,C0111

from requests import Request, Session

from flask import Blueprint, render_template, request, Response

from authlib.integrations.requests_client import OAuth2Session

from ..auth.views import authentication_required, get_auth_header, is_authenticated
from .. import app


SERVICES_ENDPOINT = app.config['PUB_URL']
# should requests verify the certificates for ssl connections
VERIFY_CERT = app.config['VERIFY_CERT']

manager = Blueprint('manager', __name__,
                    template_folder='templates',
                    static_folder='static')


@manager.route('/')
@authentication_required
def show_app(path=None):
    return render_template('manager/manager.html')


@manager.route('/services/<op1>', methods=['GET', 'POST', 'PUT', 'DELETE'])
@manager.route('/services/<op1>/<op2>', methods=['GET', 'POST', 'PUT', 'DELETE'])
@manager.route('/services/<op1>/<op2>/<op3>', methods=['GET', 'POST', 'PUT', 'DELETE'])
@manager.route('/services/<op1>/<op2>/<op3>/<op4>', methods=['GET', 'POST', 'PUT', 'DELETE'])
def services_proxy(op1, op2=None, op3=None, op4=None):
    """
    View for proxying service calls
    """
    url = '%s%s/' % (SERVICES_ENDPOINT, op1)
    if op2 is not None:
        url = url + op2
    if op3 is not None:
        url = url + '/' + op3
    if op4 is not None:
        url = url + '/' + op4

    headers = {}
    new_token = None
    if not is_authenticated():
        # Retrieve refresh token and ask for a new access token.
        oauth_session = OAuth2Session(client_id=app.config['PUBSAUTH_CLIENT_ID'],
                                      client_secret=app.config['PUBSAUTH_CLIENT_SECRET'],
                                      authorization_endpoint=app.config['PUBSAUTH_AUTHORIZE_URL'],
                                      token_endpoint=app.config['PUBSAUTH_ACCESS_TOKEN_URL'])
        refresh_token = request.cookies.get('refresh_token')

        new_token = oauth_session.refresh_token(app.config['PUBSAUTH_ACCESS_TOKEN_URL'], refresh_token=refresh_token)
        headers['Authorization'] = 'Bearer {0}'.format(new_token.get('access_token'))
    else:
        headers = get_auth_header()
    headers.update(request.headers)

    query_string = request.query_string.decode('utf-8')
    app.logger.info('Service URL is %s?%s', url, query_string)
    # Setting the query_string in the url. If we use params set to request.args, params that are repeated
    # in the query_string do not get encoded. Instead only the first one does.
    proxy_request = Request(method=request.method,
                            url='%s?%s' %(url, query_string),
                            headers=headers,
                            data=request.data)
    proxy_resp = Session().send(proxy_request.prepare(), verify=VERIFY_CERT)
    # This fixed an an ERR_INVALID_CHUNKED_ENCODING when the app was run on the deployment server.
    if 'transfer-encoding' in proxy_resp.headers:
        del proxy_resp.headers['transfer-encoding']

    resp = Response(proxy_resp.text, proxy_resp.status_code, list(proxy_resp.headers.items()))
    if new_token:
        # Update the access_token cookie
        resp.set_cookie('access_token', new_token.get('access_token'), secure=app.config['SECURE_COOKIES'])

    return resp


@manager.errorhandler(404)
def page_not_found(e):
    """
    Returns 404 (not found) status code and 404.html template.
    """
    return render_template('manager/404.html'), 404

server/pubs_ui/pubswh/views.py
"""
pubswh blueprint views
"""
# pylint: disable=C0103,C0301,C0111,W0613

from datetime import date, timedelta
import json
from operator import itemgetter
from urllib.parse import urlencode, urljoin
import random

import arrow
from dateutil import parser as dateparser
from requests import get
import tablib

from flask import render_template, abort, request, Response, jsonify, url_for, redirect, Blueprint
from flask_paginate import Pagination
from flask_mail import Message

from ..auth.views import authentication_required, is_authenticated, get_auth_header
from .. import app, mail, cache
from .canned_text import EMAIL_RESPONSE
from .forms import ContactForm, NumSeries, PublicAccessContactForm
from .utils import (pull_feed, create_display_links,
                    SearchPublications, change_to_pubs_test,
                    munge_pubdata_for_display, extract_related_pub_info,
                    update_geographic_extents, generate_sb_data, create_store_info,
                    get_altmetric_badge_img_links, generate_dublin_core, get_crossref_data, get_published_online_date,
                    check_public_access, get_unpaywall_data, make_chapter_data_for_display)
from .xml_transformations import transform_xml_full

pubswh = Blueprint('pubswh', __name__,
                   template_folder='templates',
                   static_folder='static',
                   static_url_path='/pubswh/static')
pub_url = app.config['PUB_URL']
lookup_url = app.config['LOOKUP_URL']
search_url = app.config['BASE_SEARCH_URL']
contact_recipients = app.config['CONTACT_RECIPIENTS']
ipds_contact_recipients = app.config.get('IPDS_CONTACT_RECIPIENTS')
robots_welcome = app.config.get('ROBOTS_WELCOME')
json_ld_id_base_url = app.config.get('JSON_LD_ID_BASE_URL')
google_webmaster_tools_code = app.config.get('GOOGLE_WEBMASTER_TOOLS_CODE')
preview_endpoint_url = app.config.get('PREVIEW_ENDPOINT_URL')
crossref_endpoint = app.config['CROSSREF_ENDPOINT']


# should requests verify the certificates for ssl connections
verify_cert = app.config['VERIFY_CERT']


def make_cache_key(*args, **kwargs):
    path = request.path
    args = str(hash(frozenset(request.args.items(True))))
    return path + args


@pubswh.errorhandler(404)
def page_not_found():
    # pylint: disable=W0613
    return render_template('pubswh/404.html'), 404


@pubswh.route("/preview/<index_id>")
@authentication_required
def restricted_page(index_id):
    """
    web page which is restricted and requires the user to be logged in.
    """

    # generate the auth header from the request
    auth_header = get_auth_header()

    # build the url to call the endpoint
    published_status = get(pub_url + 'publication/' + index_id,
                           params={'mimetype': 'json'}, verify=verify_cert).status_code

    # go out to manage and get the record
    response = get(preview_endpoint_url+index_id+'/preview', headers=auth_header, verify=verify_cert,
                   params={'mimetype': 'json'})

    if response.status_code == 200:
        record = response.json()
        pubdata = munge_pubdata_for_display(record, json_ld_id_base_url)
        pub_doi = pubdata.get('doi')
        pub_altmetric_badges, pub_altmetric_details = get_altmetric_badge_img_links(pub_doi, verify=verify_cert)
        small_badge = pub_altmetric_badges['small'] if pub_altmetric_badges is not None else None
        altmetric_links = {'image': small_badge, 'details': pub_altmetric_details}
        pubdata['altmetric'] = altmetric_links
        related_pubs = extract_related_pub_info(pubdata)
        if 'mimetype' in request.args and request.args.get("mimetype") == 'json':
            return jsonify(pubdata)
        return render_template("pubswh/preview.html", indexID=index_id, pubdata=pubdata, related_pubs=related_pubs)

    # if the publication has been published (so it is out of manage) redirect to the right URL
    elif response.status_code == 404 and published_status == 200:
        return redirect(url_for('pubswh.publication', index_id=index_id))

    elif response.status_code == 404 and published_status == 404:
        return render_template('pubswh/404.html'), 404


@pubswh.route('/robots.txt')
def robots():
    return render_template('pubswh/robots.txt', robots_welcome=robots_welcome)


@pubswh.route('/opensearch.xml')
def open_search():
    return render_template('pubswh/opensearch.xml')


@pubswh.route('/' + google_webmaster_tools_code + '.html')
def webmaster_tools_verification():
    return render_template('pubswh/google_site_verification.html')


@pubswh.route('/')
@cache.cached(timeout=300, key_prefix=make_cache_key, unless=is_authenticated)
def index():
    sp = SearchPublications(search_url)
    recent_publications_resp = sp.get_pubs_search_results(params={'pub_x_days': 7,
                                                                  'page_size': 6})  # bring back recent publications

    recent_pubs_content = recent_publications_resp[0]
    try:
        pubs_records = recent_pubs_content['records']
        for record in pubs_records:
            record = create_display_links(record)

    except TypeError:
        pubs_records = []  # return an empty list recent_pubs_content is None (e.g. the service is down)
    return render_template('pubswh/home.html',
                           recent_publications=pubs_records)


# contact form
@pubswh.route('/public_access_contact', methods=['GET', 'POST'])
def pub_access_contact():
    contact_form = PublicAccessContactForm()
    if request.method == 'POST':
        if contact_form.validate_on_submit():
            human_name = contact_form.name.data
            human_email = contact_form.email.data
            if human_name:
                sender_str = '({name}, {email})'.format(name=human_name, email=human_email)
            else:
                sender_str = '({email})'.format(email=human_email)
            # this is want Remedy filters on to determine if an email goes to the pubs support group
            subject_line = 'Pubs Warehouse Public Access request Comments'
            originating_page = contact_form.originating_page.data
            message_body = contact_form.message.data
            message_content = EMAIL_RESPONSE.format(contact_str=sender_str,
                                                    message_body=message_body,
                                                    originating_page=originating_page)
            msg = Message(subject=subject_line,
                          sender=(human_name, human_email),
                          reply_to=('IPDS_Help', 'GS_Help_IPDS@usgs.gov'),
                          # this is not what Remedy filters on to determine if a message
                          # goes to the pubs support group...
                          recipients=ipds_contact_recipients,
                          # will go to gs_ipds_help@usgs.gov if application has DEBUG = False
                          body=message_content)
            mail.send(msg)
            # redirect to a conf page after successful validation and message sending
            return redirect(url_for('pubswh.pub_access_contact_confirmation'))
        else:
            # redisplay the form with errors if validation fails
            return render_template('pubswh/pub_access_contact.html', contact_form=contact_form)

    contact_referrer = request.referrer
    contact_form.originating_page.data = 'Originating Page: {}'.format(contact_referrer)
    title = request.args.get('title')
    index_id = request.args.get('index_id')
    contact_form.message.data = 'I would like to request the full-text public access version of the following ' \
                                'publication: {0} \n\n USGS support team: Get more details on this publication here:' \
                                ' https://pubs.er.usgs.gov/public_access_details/{1}'.format(title, index_id)
    return render_template('pubswh/pub_access_contact.html', contact_form=contact_form)


@pubswh.route('/public_access_contact_confirm')
def pub_access_contact_confirmation():
    confirmation_message = 'Thank you for contacting the USGS Publications Warehouse Public Access support team.'
    return render_template('pubswh/pub_access_contact_confirm.html', confirm_message=confirmation_message)


@pubswh.route('/public_access_details/<index_id>')
@authentication_required
def public_access_details(index_id):
    # build the url to call the endpoint
    r = get(pub_url + 'publication/' + index_id, params={'mimetype': 'json'}, verify=verify_cert)
    if r.status_code in [404, 406]:  # a 406 pretty much always means that it is some sort of other weird malformed URL.
        return render_template('pubswh/404.html'), 404

    pubreturn = r.json()
    pubdata = munge_pubdata_for_display(pubreturn, json_ld_id_base_url)

    return render_template('pubswh/pub_access_data.html', indexID=index_id, pubdata=pubdata, related_pubs=None)


# contact form
@pubswh.route('/contact', methods=['GET', 'POST'])
def contact():
    contact_form = ContactForm()
    if request.method == 'POST':
        if contact_form.validate_on_submit():
            human_name = contact_form.name.data
            human_email = contact_form.email.data
            if human_name:
                sender_str = '({name}, {email})'.format(name=human_name, email=human_email)
            else:
                sender_str = '({email})'.format(email=human_email)
            subject_line = 'Pubs Warehouse User Comments'  # this is want Remedy filters on to determine if an email
            # goes to the pubs support group
            originating_page = contact_form.originating_page.data
            message_body = contact_form.message.data
            message_content = EMAIL_RESPONSE.format(contact_str=sender_str,
                                                    message_body=message_body,
                                                    originating_page=originating_page)
            msg = Message(subject=subject_line,

server/pubs_ui/pubswh/templates/pubswh/base.html
{% extends 'base.html' %}

{% import 'assets.html' as assets %}

{% block meta_data %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="title" content="USGS Publications Warehouse">
    <meta name="keywords" content>
    <meta name="format-detection" content="telephone=no">
    {% block head %} {% endblock %}
{% endblock %}

{% block page_style %}
    {{ super() }}
{% endblock page_style %}

{% block head_script %}
    <link rel="stylesheet" href="{{ 'pubs_base.css' | asset_url }}" type="text/css" />
    <link rel="shortcut icon" href="{{ 'images/pubswh/favicon.ico' | asset_url }}"/>
    <link rel="search" type="application/opensearchdescription+xml" href="{{ url_for('pubswh.open_search') }}" title="USGS Pubs"/>
    <link rel="unapi-server" type="application/xml" title="unAPI" href="{{ url_for('pubswh.unapi') }}" />
    <link rel="alternate" type="application/rss+xml" title="USGS Publications Warehouse RSS Feed" href="https://pubs.er.usgs.gov/pubs-services/publication/rss"/>
    <script>
        var CONFIG = {
            lookupUrl: '{{ config.LOOKUP_URL }}',
            requestArgs: JSON.parse('{{ request.args.to_dict(False)|tojson }}') <!-- set to True if only one value per key is desired -->
        }
    </script>
{% endblock %}

{% block usgs_header %}
    {{ header.usgs_header("enable_nav", is_authenticated) }}
{% endblock  %}

{% block main %}
    {% if ANNOUNCEMENT_BLOCK|length > 0 %}
        <span id="announcement" style="font-size: 150%; padding: 15px;"></span>
        <script>
            document.getElementById('announcement').innerHTML = '{{ ANNOUNCEMENT_BLOCK|safe }}';
        </script>
    {% endif %}

    <div class="usa-prose">
        {% block main_pubswh %}{% endblock %}
    </div>

{% endblock main %}

{% block page_script %}
    {{ assets.LoadBundle('pubswh_plugins.js') }}
    <script async type="application/javascript"
            src="https://www2.usgs.gov/scripts/analytics/usgs-analytics.js"></script>

   {% block page_footer_script %}{% endblock page_footer_script %}

   <script>
       var GA = {};
       (function (i, s, o, g, r, a, m) {
           i['GoogleAnalyticsObject'] = r;
           i[r] = i[r] || function () {
                   (i[r].q = i[r].q || []).push(arguments)
               }, i[r].l = 1 * new Date();
           a = s.createElement(o),
               m = s.getElementsByTagName(o)[0];
           a.async = 1;
           a.src = g;
           m.parentNode.insertBefore(a, m)
       })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

       ga('create', '{{ GOOGLE_ANALYTICS_CODE }}', 'auto');
       ga('send', 'pageview');

       GA.trackGAEvent = function (category, actions, labels, values) {
           ga('send', 'event', category, actions, labels, values);
       };
   </script>
{% endblock %}

server/pubs_ui/pubswh/templates/pubswh/browse_series_years.html
{% extends 'pubswh/base.html' %}

{% block head %}
    <title>Browse the USGS Publications Warehouse</title>
    <meta name="description" content="Browse all of the USGS publications warehouse by following a link tree">
{% endblock %}

{% block main_pubswh %}
<div class="browse-page">
    <p class="breadcrumb">
        <a href="{{ url_for('pubswh.index') }}" title="Pubs Warehouse Home">Pubs Warehouse Home</a>
        <span> &gt; </span><a href="{{ url_for('pubswh.browse_types') }}" title="Browse USGS Publications">Browse</a>
        {% if pub_type %}<span> &gt; </span><a href="{{ url_for("pubswh.browse_subtypes", pub_type=pub_type) }}">{{ pub_type }}</a>{% endif %}
        {% if pub_subtype %}<span> &gt; </span><a href="{{ url_for("pubswh.browse_subtype", pub_type=pub_type, pub_subtype=pub_subtype) }}">{{ pub_subtype }}</a>{% endif %}
        {% if series_title %}<span> &gt; </span><a href="{{ url_for("pubswh.browse_series", pub_type=pub_type, pub_subtype=pub_subtype, pub_series_name=series_title) }}">{{ series_title }}</a>{% endif %}
    </p>

    <h1>Browse the USGS Publication Warehouse</h1>
    <h2>Years that the {{ pub_type }} {{ series_title }} may be available</h2>
    <ul>
        {% for year in year_range %}
            <li>
               <a class="usa-link" href="{{ url_for("pubswh.browse_series_year", pub_type=pub_type, pub_subtype=pub_subtype, pub_series_name=series_title, year=year ) }}">{{ year }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

server/pubs_ui/pubswh/templates/pubswh/browse_subtype.html
{% extends 'pubswh/base.html' %}

{% block head %}
    <title>Browse the USGS Publications Warehouse</title>
    <meta name="description" content="Browse all of the USGS publications warehouse by following a link tree">
{% endblock %}

{% block main_pubswh %}
<div class="browse-page">
    <p class="breadcrumb"> <a href="{{ url_for('pubswh.index') }}" title="Pubs Warehouse Home">Pubs Warehouse Home</a>
        <span> &gt; </span><a href="{{ url_for('pubswh.browse_types') }}" title="Browse USGS Publications">Browse</a>
        {% if pub_type %}<span> &gt; </span><a href="{{ url_for("pubswh.browse_subtypes", pub_type=pub_type) }}">{{ pub_type }}</a>{% endif %}
        {% if pub_subtype %}<span> &gt; </span><a href="{{ url_for("pubswh.browse_subtype", pub_type=pub_type, pub_subtype=pub_subtype) }}">{{ pub_subtype }}</a>{% endif %}
    </p>
    <h1>Browse the USGS Publication Warehouse</h1>
    <h2>Series for the publication type {{ pub_type }} and subtype {{ pub_subtype }}</h2>
    <ul>
        {% for series in series_titles %}
            <li>
               <a class="usa-link" title="see the publications associated with this series" href="{{ url_for("pubswh.browse_series", pub_type=pub_type, pub_subtype=pub_subtype, pub_series_name=series['text']) }}" #}>{{ series['text'] }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

server/pubs_ui/pubswh/templates/pubswh/home.html
{% extends 'pubswh/base.html' %}
{% block head %}
    <title>U.S. Geological Survey Publications Warehouse</title>
    <meta name="description"
          content="The Publications warehouse contains over 150,000 publications that cover the 150 year history of the USGS">
    {% include 'pubswh/meta.html' %}
{% endblock head %}

{% block page_style %}
    {{ super() }}
    <link rel="stylesheet" href="{{ 'vendor/leaflet/leaflet.css' | asset_url }}">
    <link rel="stylesheet" href="{{ 'vendor/leaflet-draw/leaflet.draw.css' | asset_url }}">
{% endblock page_style %}

{% block main_pubswh %}
    <section id="welcome">
        <h1>USGS Publications Warehouse</h1>
        <p>The Pubs Warehouse provides access to over 160,000 publications written by USGS scientists over the
            century-plus history of the bureau.</p>
    </section>
    <div id="home-page-content">
        <div class="grid-row">
            <div id="search-and-new-pubs-content">
                {% include 'pubswh/search_form.html' %}
                <aside id="new-pubs">
                    <h3><a href="{{ url_for('pubswh.new_pubs') }}">New
                        Publications by USGS Authors</a></h3>

                    {% for recent_publication in recent_publications %}
                        <div>
                            <img class="thumbnail" src="
                                    {{ wsgi_str }}{% if recent_publication['displayLinks']['Thumbnail'][0]['url'] %}{{ url_for('images', filename=recent_publication['displayLinks']['Thumbnail'][0]['url'], width=50, format='PNG') }}{% else %}{{ url_for('pubswh.images', filename='http://pubs.er.usgs.gov/thumbnails/usgs_thumb.jpg', width=50) }}{% endif %}"
                                                             alt="thumbnail"/>
                            <div class="recent-pub">
                                <div class="recent-pub-title">
                                    <a href="{{ url_for('pubswh.publication', index_id = recent_publication['indexId']) }}">{{ recent_publication['title']|safe }}</a>
                                </div>
                                <div class="recent-pub-info">
                                    {{ recent_publication|display_pub_info }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </aside>
            </div>
            <div id="twitter">
                <a class="twitter-timeline" data-theme="dark" data-height="600px"
                   href="https://twitter.com/USGS_Pubs?ref_src=twsrc%5Etfw">Tweets by USGS_Pubs</a>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_footer_script %}

    {% include "pubswh/search_form_script.html" %}
    <!-- This basically catches links that were built on the old search parameter url design, which was all in the "fragment" after the hash -->
    <script type="text/javascript">
        //grab the contents of the fragment
        var searchstring = window.location.href.split('#')[1];
        //pass the contents of the fragment to the legacysearch endpoint for further munging and redirection
        if (searchstring) {
            window.location = "/legacysearch/" + searchstring;
        }
    </script>

{% endblock page_footer_script %}

server/pubs_ui/pubswh/templates/pubswh/meta.html
        <meta name="authors" content="William Blondeau, Stephan Kochaver, James Kreft, Martin Wernimont, Andrew Yan, Mary Bucknell">
        <meta name="publisher" content="USGS Center for Integrated Data Analytics">
        <meta name="country" content="USA">
        <meta name="language" content="EN">
        <meta name="revised" content>
        <meta name="review" content>
        <meta name="expires" content="never">

server/pubs_ui/pubswh/templates/pubswh/other_resources.html
{% extends 'pubswh/base.html' %}

{% block head %}
    <title>Other Publications Resources- USGS Publications Warehouse</title>
    <meta name="description" content="Other places to get information from the US Geological Survey">
    {% include 'pubswh/meta.html' %}
{% endblock %}

{% block main_pubswh %}
    <h1>Other Resources</h1>
    {{ other_resources|safe }}
{% endblock %}

server/pubs_ui/pubswh/templates/pubswh/search_results.html
{% extends 'pubswh/base.html' %}

{% block head %}
    <title>Search Results - USGS Publications Warehouse</title>
    <meta name="description" content="Search results for USGS Publications Warehouse">

    {% include 'pubswh/meta.html' %}

    <meta name="totalResults" content="{{ result_summary['record_count'] }}"/>
    <meta name="startIndex" content="{{ result_summary['record_min'] }}"/>
    <meta name="itemsPerPage" content="{{ result_summary['records_per_page'] }}"/>
{% endblock head %}

{% block page_style %}
    {{ super() }}
    <link rel="stylesheet" href="{{ 'vendor/leaflet/leaflet.css' | asset_url }}">
    <link rel="stylesheet" href="{{ 'vendor/leaflet-draw/leaflet.draw.css' | asset_url }}">
{% endblock page_style %}

{% block main_pubswh %}

    {% if pagination %}
        <h1 class="search-results">Search Results</h1>

        {% include 'pubswh/search_form.html' %}
        {% macro pub_service_url(mimetype, disp_mimetype) %}
            <a href="{{ config.BASE_SEARCH_URL }}?mimeType={{ mimetype }}&{{ query_request_string }}">{{ disp_mimetype }}</a>
        {% endmacro %}

        <section id="search-result-summary">
            <p>{{ result_summary['record_count'] }} results.</p>
            <p>Alternate formats:
                <a href="{{ json_ld_base_url }}/search?page_size=3000&mimetype=ris&{{ query_request_string }}">
                    {% if result_summary['record_count'] <= 3000 %}
                        Download search results as RIS
                    {% else %}
                        RIS file of the first 3000 search results
                    {% endif %}
                </a>
                <strong>&nbsp;|&nbsp;</strong>
                {% if result_summary['record_count'] > 3000 %}
                    Download all results as
                {% endif %}
                {{ pub_service_url("csv", "CSV") }} | {{ pub_service_url('tsv', 'TSV') }} | {{ pub_service_url('xlsx', 'Excel') }}
                <strong>&nbsp;|&nbsp;</strong>
                <a href="{{ config.BASE_SEARCH_URL }}rss/?pub_x_days=60&{{ query_request_string }}">RSS feed based on this search</a>
                <strong>&nbsp;|&nbsp;</strong>
                <a href="{{ config.BASE_SEARCH_URL }}?page_size={{ result_summary['records_per_page'] }}&page_number={{ result_summary['page_number'] }}&{{ query_request_string }}">
                    JSON version of this page of results
                </a>
            </p>
            <p>Page {{ result_summary['page_number'] }}, results {{ result_summary['record_min'] }} - {{ result_summary['record_max'] }}</p>
            <p>
                <a class="toggle-results-map-btn" href="#">Show results on a map</a>
            </p>
        </section>

        {% include 'pubswh/search_results_map.html' %}

        <section id="search-results">
                {% for result in search_result_records %}
                    <article>
                        <cite class="search-result-title">
                            <a href="{{ url_for('pubswh.publication', index_id = result['indexId']) }}">
                                {{ result['title']|safe }}
                            </a>
                        </cite>
                        {% if is_authenticated %}
                            <a class="edit-pub-link" href="{{ url_for('manager.show_app')}}#publication/{{ result['id'] }}" target="_blank">(edit in Manager)</a></small>
                        {% endif %}
                        {% if result['authorsList']|length > 0 %}
                            <div class="search-result-contributors">{{ result['authorsList']|join(', ') }}</div>
                        {% endif %}
                        {% if result['editorsList']|length > 0 %}
                            <div class="search-result-contributors">{{ result['editorsList']|join(', ') }}, editor(s)</div>
                        {% endif %}
                        <div class="search-result-pubinfo">{{ result|display_pub_info }}</div>
                        {% if result['docAbstract']  %}
                            <div class="search-result-abstract">{{ result['docAbstract'].split(' ')[0:50]|join(' ')|striptags }}...</div>
                        {% endif %}
                    </article>
                {% endfor %}
        </section>

        <section class="pagination-nav">
            {{ pagination.links|safe }}
        </section>
    {% else %}
        {{ search_service_down }}
    {% endif %}
{% endblock main_pubswh %}

{% block page_footer_script %}
    {% include "pubswh/search_form_script.html" %}
    {% include 'pubswh/search_results_map_script.html' %}
{% endblock page_footer_script %}

server/pubs_ui/pubswh/templates/pubswh/search_results_map.html
<section id="extents-map-section">
    <h4>Publication Extents</h4>
    <div id="extents-map"></div>
    <small>Not all publications have extents, not all extents are completely accurate</small>
</section>